language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.6.5
cache:
  directories:
    - $HOME/.pip-cache/
    - /home/travis/virtualenv/python2.7
install:
  - pip install -q flake8==2.2.0 --download-cache $HOME/.pip-cache
  - pip install -q coverage==3.7.1 coveralls==0.4.2 --download-cache $HOME/.pip-cache
  - pip install -r requirements.txt --download-cache $HOME/.pip-cache
  - pip install -q Django==$DJANGO_VERSION --download-cache $HOME/.pip-cache
before_script:
  - flake8 --max-line-length=160 --max-complexity=10 --statistics --benchmark .
script:
  - coverage run manage.py test
  - coverage report
after_success:
  - coveralls
